/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vérifie la disponibilité de l'API
         * @description Sonde de connectivité : sert de test de bout en bout du squelette (Lot 0) et, plus tard, de vérification réseau côté PWA offline-first.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cartes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recherche dans le catalogue
         * @description Cartes du catalogue VEKN, triées par nom. `q` cherche dans le nom anglais (sous-chaîne, sans tenir compte de la casse ni des accents). Chaque carte porte ses extensions d'impression et celle de sa dernière version (`latest_card_set_id`).
         */
        get: operations["listCards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cartes/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fiche complète d'une carte */
        get: operations["getCard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extensions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Extensions du catalogue
         * @description Toutes les extensions, des plus anciennes aux plus récentes, les extensions sans date en dernier. `is_placeholder` signale l'extension tampon de l'import (cartes publiées sans impression).
         */
        get: operations["listCardSets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bundles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Produits (précons, boîtes)
         * @description `q` cherche dans le nom du produit (sous-chaîne, sans tenir compte de la casse ni des accents).
         */
        get: operations["listBundles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bundles/{bundle_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contenu d'un produit */
        get: operations["getBundle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bundles/{bundle_id}/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verser un produit dans la collection
         * @description Ajoute le contenu du produit au stock, dans la langue indiquée et sous l'extension du produit. Les quantités s'additionnent à l'existant. Non idempotent : deux appels versent deux produits. 409 si le produit est sans contenu connu, ou si le total d'une entrée dépasserait le plafond (2147483647) : aucune entrée n'est alors modifiée.
         */
        post: operations["depositBundle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/langues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Langues d'exemplaires */
        get: operations["listLanguages"];
        put?: never;
        /** Ajouter une langue */
        post: operations["createLanguage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liste la collection
         * @description `q` cherche dans le nom anglais de la carte (sous-chaîne, sans tenir compte de la casse ni des accents).
         */
        get: operations["listStock"];
        put?: never;
        /**
         * Déclare une carte dans une langue et une extension
         * @description 404 si la carte, la langue ou l'extension est inconnue, ou si la carte n'a pas été imprimée dans cette extension. 409 si l'entrée existe déjà.
         */
        post: operations["createStockEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stock/{card_id}/{language_code}/{card_set_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lit une entrée de collection */
        get: operations["getStockEntry"];
        put?: never;
        post?: never;
        /**
         * Retire une entrée de collection
         * @description Refusé (409) tant que des decks utilisent l'entrée.
         */
        delete: operations["deleteStockEntry"];
        options?: never;
        head?: never;
        /** Modifie une entrée de collection */
        patch: operations["updateStockEntry"];
        trace?: never;
    };
    "/decks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liste les decks
         * @description `state` choisit les decks listés : `active` (défaut, les non archivés), `archived` ou `all` (archivés compris). Les decks supprimés n'apparaissent jamais, quel que soit `state` ; `status` (draft, active) et `q` (sous-chaîne du nom, sans tenir compte de la casse ni des accents) filtrent en plus. Tri par nom puis discriminant.
         */
        get: operations["listDecks"];
        put?: never;
        /**
         * Crée un deck
         * @description Le serveur tire un discriminant de quatre chiffres (« Malkavien 2022#8561 ») : deux decks peuvent porter le même nom, il n'y a jamais de 409 pour un nom déjà pris. Un deck neuf est vide : le créer directement `active` est refusé (409) ; le créer en `draft`, le composer, puis l'activer. 409 aussi si aucun discriminant libre ne peut être attribué au nom (espace saturé, ou écritures concurrentes répétées).
         */
        post: operations["createDeck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deck_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Un deck et sa composition
         * @description Renvoie aussi les decks supprimés, en lecture seule : `deleted_at` est alors renseigné et `cards` vient de la decklist figée à la suppression (même forme et même tri qu'un deck vivant : crypt d'abord, puis nom, puis langue). Un identifiant inconnu est un 404.
         */
        get: operations["getDeck"];
        put?: never;
        post?: never;
        /**
         * Supprime un deck archivé (suppression logique)
         * @description Réservé aux decks archivés (409 sinon, et 409 si le deck est déjà supprimé). Suppression logique : la decklist est figée (recopiée dans la decklist du deck supprimé) et les lignes vivantes disparaissent, ce qui rend les exemplaires et les proxies au stock ; le deck et ses participations restent en base. Le deck n'apparaît plus dans aucune liste mais reste lisible par `GET /decks/{id}`.
         */
        delete: operations["deleteDeck"];
        options?: never;
        head?: never;
        /**
         * Modifie un deck
         * @description `archived: true` archive le deck (`archived_at` posé s'il ne l'est pas : rejouer la requête garde la date d'origine) ; `archived: false` le sort de l'archive. Un deck archivé n'est modifiable que pour être désarchivé : tout autre champ est refusé (409) sauf si la requête contient `archived: false` (le désarchivage précède alors les autres modifications) ; `{"archived": true}` seul reste un 200 sans effet. Passer un deck à `active` exige qu'il soit légal (cf. `/decks/{id}/legalite`) ; sinon 409. Renommer conserve le discriminant, sauf si le couple (nom, discriminant) est déjà pris : un autre est alors tiré. Un deck supprimé n'est plus modifiable (409).
         */
        patch: operations["updateDeck"];
        trace?: never;
    };
    "/decks/{deck_id}/legalite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Légalité du deck
         * @description Calculée à la demande, à la date du jour (UTC, rappelée dans `evaluated_on`) : tailles de crypt et de library, groupes adjacents, cartes bannies, cartes pas encore légales. Les seuils voyagent dans la réponse. Portée par la composition vivante : 409 pour un deck supprimé.
         */
        get: operations["getDeckLegality"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deck_id}/cartes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ajoute une carte au deck
         * @description La carte doit être en collection dans la langue et l'extension demandées, avec assez d'exemplaires disponibles (hors proxies) ; sinon 409. Aussi 409 si le deck est archivé ou supprimé. 404 si la carte n'a pas été imprimée dans cette extension.
         */
        post: operations["addDeckCard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deck_id}/cartes/{card_id}/{language_code}/{card_set_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Retire une carte du deck
         * @description Un deck archivé ou supprimé n'est pas modifiable (409).
         */
        delete: operations["removeDeckCard"];
        options?: never;
        head?: never;
        /**
         * Modifie une ligne du deck
         * @description Refusé (409) si le deck est archivé ou supprimé, si le proxy n'est pas autorisé ou si les exemplaires disponibles ne suffisent pas.
         */
        patch: operations["updateDeckCard"];
        trace?: never;
    };
    "/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rejoue un lot d'écritures faites hors ligne
         * @description Rejoue la file d'attente du client : un lot ordonné d'opérations, chacune portant sa clé d'idempotence (`operation_id`). Le lot ne bascule jamais en bloc — chaque opération reçoit son verdict (`applied`, `replayed`, `rejected`) dans l'ordre de la requête, et un refus n'interrompt pas les suivantes. Rejouer une clé déjà tranchée rend le verdict mémorisé sans rien réappliquer ; c'est ce qui rend le versement d'un produit (`bundle.deposit`) sûr au rejeu, là où `POST /bundles/{bundle_id}/stock` additionne à chaque appel. Un deck créé hors ligne se désigne par la référence client de sa création, le serveur restant seul à attribuer identifiant et discriminant. Ni 404 ni 409 ne sortent de cette route : un refus est un verdict dans le corps de la réponse 200. Le seul autre code est un 503 transitoire, quand une écriture concurrente tient la base — rien n'a alors été appliqué, et le lot se renvoie à l'identique.
         */
        post: operations["syncOperations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BundleCardRead
         * @description Une ligne du contenu d'un produit : une carte, en n exemplaires.
         */
        BundleCardRead: {
            card: components["schemas"]["CardSummary"];
            /** Copies */
            copies: number;
        };
        /**
         * BundleContentRead
         * @description Contenu complet d'un produit.
         *
         *     Réponse d'un futur `GET /bundles/{id}` (Lot 2). Deux usages la motivent :
         *     savoir quel produit acheter pour compléter un deck, et verser ce contenu
         *     dans la collection — `cards` a exactement la forme qu'attend une création
         *     d'entrées de stock (carte + quantité), à laquelle il ne manque que la
         *     langue de l'exemplaire acheté.
         *
         *     Le service assemble ces lignes depuis les occurrences de type « precon »
         *     du produit ; ce n'est pas une relation ORM directe, la carte se trouvant
         *     un cran plus loin, derrière l'impression.
         */
        BundleContentRead: {
            /** Id */
            id: number;
            /** Card Set Id */
            card_set_id: number;
            /** Code */
            code: string;
            /** Name */
            name: string | null;
            /**
             * Size
             * @description Nombre de cartes annoncé par le produit. Déclaratif : ne colle pas toujours exactement au contenu listé.
             */
            size: number | null;
            /** Release Date */
            release_date: string | null;
            /**
             * Cards
             * @default []
             */
            cards: components["schemas"]["BundleCardRead"][];
        };
        /**
         * BundleDeposit
         * @description Versement du contenu d'un produit dans la collection.
         *
         *     Le produit fixe les cartes et leurs exemplaires ; il ne manque que la
         *     langue de ce qui a été acheté, et le nombre de produits identiques.
         *     L'extension n'y figure pas (Lot 4) : chaque carte est rangée sous
         *     l'extension du produit (`BundleRead.card_set_id`), dont elle est toujours
         *     une impression.
         */
        BundleDeposit: {
            /** Language Code */
            language_code: string;
            /**
             * Count
             * @description Nombre de produits identiques versés d'un coup.
             * @default 1
             */
            count?: number;
        };
        /**
         * BundleDepositOperation
         * @description Verse le contenu d'un produit dans la collection.
         *
         *     L'opération qui justifie à elle seule le journal : hors `/sync`,
         *     `POST /bundles/{id}/stock` additionne le produit à chaque appel, donc un
         *     rejeu double le stock. Passée par ici, elle est tranchée une fois pour
         *     toutes — un second envoi de la même clé d'idempotence est « rejouée », sans
         *     effet.
         */
        BundleDepositOperation: {
            /**
             * Operation Id
             * Format: uuid
             * @description Clé d'idempotence tirée par le client (UUID), fixée à la saisie et jamais réutilisée. Rejouer le même identifiant rend le verdict d'origine sans rien réappliquer.
             */
            operation_id: string;
            /**
             * Recorded At
             * Format: date-time
             * @description Instant de la saisie à l'horloge du client, fuseau obligatoire, normalisé en UTC. Journalisé ; sans effet sur les règles métier.
             */
            recorded_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "bundle.deposit";
            /** Bundle Id */
            bundle_id: number;
            data: components["schemas"]["BundleDeposit"];
        };
        /**
         * BundleRead
         * @description Produit vendu dans une extension (deck préconstruit, boîte…).
         *
         *     L'unité d'achat : ce qu'on vise pour compléter un deck, et ce qu'on verse
         *     dans la collection d'un seul geste. `code` peut être vide — 14 extensions
         *     n'ont qu'un précon, sans code propre.
         */
        BundleRead: {
            /** Id */
            id: number;
            /** Card Set Id */
            card_set_id: number;
            /** Code */
            code: string;
            /** Name */
            name: string | null;
            /**
             * Size
             * @description Nombre de cartes annoncé par le produit. Déclaratif : ne colle pas toujours exactement au contenu listé.
             */
            size: number | null;
            /** Release Date */
            release_date: string | null;
        };
        /**
         * CardCategory
         * @description Les deux moitiés d'un deck VtES (CLAUDE.md §5).
         * @enum {string}
         */
        CardCategory: "crypt" | "library";
        /**
         * CardCopyCreate
         * @description Déclaration d'une entrée de collection.
         */
        CardCopyCreate: {
            /** Card Id */
            card_id: number;
            /** Language Code */
            language_code: string;
            /**
             * Card Set Id
             * @description Extension de l'impression (`GET /extensions`). Le couple carte × extension doit être une impression du catalogue (`CardRead.card_set_ids`), sinon 404.
             */
            card_set_id: number;
            /**
             * Quantity Owned
             * @default 0
             */
            quantity_owned?: number;
            /** Notes */
            notes?: string | null;
        };
        /**
         * CardCopyRead
         * @description Exemplaires possédés d'une carte, dans une langue, pour une impression.
         */
        CardCopyRead: {
            /** Card Id */
            card_id: number;
            /** Language Code */
            language_code: string;
            /**
             * Card Set Id
             * @description Extension de l'impression possédée (`GET /extensions`).
             */
            card_set_id: number;
            /**
             * Quantity Owned
             * @description Nombre d'exemplaires réellement possédés. Une entrée à 0 est valide : c'est ainsi qu'une carte jouée uniquement en proxy entre en collection.
             */
            quantity_owned: number;
            /** Notes */
            notes: string | null;
            card: components["schemas"]["CardSummary"] | null;
        };
        /**
         * CardCopyUpdate
         * @description Modification d'une entrée de collection.
         *
         *     La carte, la langue et l'extension forment la clé : elles ne se modifient
         *     pas, on crée une autre entrée. `quantity_owned` est facultatif mais non nullable
         *     (colonne NOT NULL) ; `notes`, lui, accepte `null` pour effacer la note.
         *     L'autorisation de proxy n'est plus ici : elle appartient au deck.
         */
        CardCopyUpdate: {
            /** Quantity Owned */
            quantity_owned?: number;
            /** Notes */
            notes?: string | null;
        };
        /**
         * CardDisciplineRead
         * @description Discipline requise par une carte, avec son niveau.
         */
        CardDisciplineRead: {
            discipline: components["schemas"]["DisciplineRead"];
            /**
             * Superior
             * @description Niveau supérieur (code en majuscules chez krcg).
             */
            superior: boolean;
        };
        /**
         * CardListItem
         * @description Une carte dans les résultats de recherche, avec ses impressions (Lot 4).
         *
         *     Ce que le client hors ligne doit connaître pour ranger un exemplaire sous
         *     une impression réelle sans rappeler l'API : les extensions où la carte a
         *     été imprimée, et celle qu'il faut prendre par défaut quand la carte entre
         *     en collection pour être jouée en proxy (décision D2a).
         *
         *     Distinct de `CardSummary`, qui reste la vue courte embarquée dans le
         *     stock, les decks et les produits : ces deux champs n'y ont pas d'usage.
         */
        CardListItem: {
            /** Id */
            id: number;
            /** Vekn Id */
            vekn_id: number;
            /** Name */
            name: string;
            category: components["schemas"]["CardCategory"];
            clan: components["schemas"]["ClanRead"] | null;
            /** Capacity */
            capacity: number | null;
            /** Group Code */
            group_code: string | null;
            /**
             * Advanced
             * @default false
             */
            advanced: boolean;
            /**
             * Image Url
             * @description Scan de la carte (version anglaise de référence).
             */
            image_url: string | null;
            /**
             * Card Set Ids
             * @description Extensions où la carte a été imprimée (`GET /extensions`), triées par identifiant. Jamais vide : toute carte a au moins une impression, au besoin sous l'extension tampon.
             * @default []
             */
            card_set_ids: number[];
            /**
             * Latest Card Set Id
             * @description Extension de la dernière version de la carte, calculée par le serveur : date la plus récente parmi les occurrences de l'impression (à défaut, la date de l'extension) ; à date égale, une extension datée passe avant une extension sans date, puis la première abréviation par ordre alphabétique. L'extension tampon ne compte que si elle est la seule. Impression par défaut d'une carte ajoutée en collection pour être jouée en proxy.
             */
            latest_card_set_id: number;
        };
        /**
         * CardPrintingOccurrenceRead
         * @description Comment une carte apparaît dans une extension.
         *
         *     Les champs renseignés dépendent du type : fréquence et multiplicateur pour
         *     un booster, produit et exemplaires pour un précon, date pour une promo.
         */
        CardPrintingOccurrenceRead: {
            occurrence_type: components["schemas"]["PrintOccurrence"];
            /**
             * Frequency
             * @description Code de rareté en booster (C, U, R, V…).
             */
            frequency: string | null;
            /**
             * Multiplier
             * @description Nombre moyen d'exemplaires par booster (0,5 possible).
             */
            multiplier: number | null;
            /**
             * Copies
             * @description Nombre d'exemplaires dans le produit, pour un précon.
             */
            copies: number | null;
            /** Released On */
            released_on: string | null;
            bundle: components["schemas"]["BundleRead"] | null;
        };
        /**
         * CardPrintingRead
         * @description Présence d'une carte dans une extension, et par quels produits.
         */
        CardPrintingRead: {
            card_set: components["schemas"]["CardSetRead"];
            /**
             * Image Url
             * @description Scan de la carte telle qu'imprimée dans cette extension.
             */
            image_url: string | null;
            /**
             * Occurrences
             * @default []
             */
            occurrences: components["schemas"]["CardPrintingOccurrenceRead"][];
        };
        /**
         * CardRead
         * @description Fiche complète d'une carte du catalogue.
         */
        CardRead: {
            /** Id */
            id: number;
            /** Vekn Id */
            vekn_id: number;
            /** Name */
            name: string;
            category: components["schemas"]["CardCategory"];
            clan: components["schemas"]["ClanRead"] | null;
            /** Capacity */
            capacity: number | null;
            /** Group Code */
            group_code: string | null;
            /**
             * Advanced
             * @default false
             */
            advanced: boolean;
            /**
             * Image Url
             * @description Scan de la carte (version anglaise de référence).
             */
            image_url: string | null;
            /**
             * Card Set Ids
             * @description Extensions où la carte a été imprimée (`GET /extensions`), triées par identifiant. Jamais vide : toute carte a au moins une impression, au besoin sous l'extension tampon.
             * @default []
             */
            card_set_ids: number[];
            /**
             * Latest Card Set Id
             * @description Extension de la dernière version de la carte, calculée par le serveur : date la plus récente parmi les occurrences de l'impression (à défaut, la date de l'extension) ; à date égale, une extension datée passe avant une extension sans date, puis la première abréviation par ordre alphabétique. L'extension tampon ne compte que si elle est la seule. Impression par défaut d'une carte ajoutée en collection pour être jouée en proxy.
             */
            latest_card_set_id: number;
            sect: components["schemas"]["SectRead"] | null;
            /** Title */
            title: string | null;
            /** Path */
            path: string | null;
            /** @description Nature du coût : une carte n'en a jamais qu'un seul. */
            cost_type: components["schemas"]["CostType"] | null;
            /**
             * Cost Value
             * @description Montant du coût. Chaîne et non entier : 25 cartes coûtent « X ».
             */
            cost_value: string | null;
            /**
             * Burn Option
             * @default false
             */
            burn_option: boolean;
            /**
             * Trifle
             * @default false
             */
            trifle: boolean;
            /**
             * Clan Requirement
             * @description Clan(s) exigé(s) par la carte, séparés par une virgule.
             */
            clan_requirement: string | null;
            /** Path Requirement */
            path_requirement: string | null;
            /** @description Manière de combiner les disciplines listées : une seule, au choix, ou toutes ensemble. */
            discipline_requirement: components["schemas"]["DisciplineRequirement"] | null;
            /** Card Text */
            card_text: string | null;
            /** Flavor Text */
            flavor_text: string | null;
            /** Artist */
            artist: string | null;
            /**
             * Banned On
             * @description Date de bannissement publiée par le VEKN, vide sinon.
             */
            banned_on: string | null;
            /**
             * Legal From
             * @description Date d'entrée en légalité en tournoi. Vide = aucune information, donc légale : la liste paraît après la sortie commerciale.
             */
            legal_from: string | null;
            /**
             * Types
             * @default []
             */
            types: components["schemas"]["CardTypeRead"][];
            /**
             * Discipline Links
             * @default []
             */
            discipline_links: components["schemas"]["CardDisciplineRead"][];
            /**
             * Printings
             * @default []
             */
            printings: components["schemas"]["CardPrintingRead"][];
            /**
             * Translations
             * @default []
             */
            translations: components["schemas"]["CardTranslationRead"][];
        };
        /**
         * CardSetRead
         * @description Extension.
         *
         *     Liste servie par `GET /extensions` (Lot 4) : le client hors ligne s'en sert
         *     pour proposer, et afficher, l'extension d'une entrée de collection.
         */
        CardSetRead: {
            /** Id */
            id: number;
            /** Abbrev */
            abbrev: string;
            /** Full Name */
            full_name: string | null;
            /** Release Date */
            release_date: string | null;
            /** Company */
            company: string | null;
            /**
             * Is Placeholder
             * @description Extension tampon créée par l'import pour une carte publiée sans aucune impression (une seule pour tout le catalogue). Une entrée rangée dessous est à réattribuer à une vraie extension dès que la source sera corrigée.
             * @default false
             */
            is_placeholder: boolean;
        };
        /**
         * CardSummary
         * @description Vue courte d'une carte, pour les listes et l'autocomplétion.
         */
        CardSummary: {
            /** Id */
            id: number;
            /** Vekn Id */
            vekn_id: number;
            /** Name */
            name: string;
            category: components["schemas"]["CardCategory"];
            clan: components["schemas"]["ClanRead"] | null;
            /** Capacity */
            capacity: number | null;
            /** Group Code */
            group_code: string | null;
            /**
             * Advanced
             * @default false
             */
            advanced: boolean;
            /**
             * Image Url
             * @description Scan de la carte (version anglaise de référence).
             */
            image_url: string | null;
        };
        /**
         * CardTranslationRead
         * @description Libellés localisés d'une carte.
         *
         *     Distinct de la collection : traduire une carte ne dit rien sur le fait de
         *     la posséder, et posséder un exemplaire en français ne suppose pas qu'on
         *     connaisse sa traduction officielle.
         */
        CardTranslationRead: {
            /** Language Code */
            language_code: string;
            /** Name */
            name: string;
            /** Card Text */
            card_text: string | null;
            /** Flavor Text */
            flavor_text: string | null;
            /**
             * Image Url
             * @description Scan de la version localisée, quand il existe.
             */
            image_url: string | null;
        };
        /**
         * CardTypeRead
         * @description Type de carte.
         */
        CardTypeRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * ClanRead
         * @description Clan.
         */
        ClanRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Abbrev */
            abbrev: string | null;
        };
        /**
         * CostType
         * @description Nature du coût d'une carte de library.
         *
         *     krcg n'expose qu'un coût par carte (`{"type": ..., "value": ...}`) : une
         *     carte ne coûte jamais à la fois du sang et du pool.
         * @enum {string}
         */
        CostType: "pool" | "blood" | "conviction";
        /**
         * DeckCardCreate
         * @description Ajout d'une carte à un deck.
         *
         *     La carte doit déjà exister dans la collection pour la langue et
         *     l'extension demandées (CLAUDE.md §11 point 2) ; la vérification de
         *     disponibilité relève du service, la base garantissant déjà l'existence de
         *     l'entrée de collection.
         */
        DeckCardCreate: {
            /** Quantity */
            quantity: number;
            /**
             * Proxy Quantity
             * @default 0
             */
            proxy_quantity?: number;
            /** Card Id */
            card_id: number;
            /** Language Code */
            language_code: string;
            /**
             * Card Set Id
             * @description Extension de l'impression (`GET /extensions`). Le couple carte × extension doit être une impression du catalogue (`CardRead.card_set_ids`), sinon 404.
             */
            card_set_id: number;
        };
        /**
         * DeckCardDeleteOperation
         * @description Retire une carte d'un deck.
         */
        DeckCardDeleteOperation: {
            /**
             * Operation Id
             * Format: uuid
             * @description Clé d'idempotence tirée par le client (UUID), fixée à la saisie et jamais réutilisée. Rejouer le même identifiant rend le verdict d'origine sans rien réappliquer.
             */
            operation_id: string;
            /**
             * Recorded At
             * Format: date-time
             * @description Instant de la saisie à l'horloge du client, fuseau obligatoire, normalisé en UTC. Journalisé ; sans effet sur les règles métier.
             */
            recorded_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "deck_card.delete";
            deck: components["schemas"]["DeckRef"];
            /** Card Id */
            card_id: number;
            /** Language Code */
            language_code: string;
            /**
             * Card Set Id
             * @description Extension de l'impression (`GET /extensions`). Le couple carte × extension doit être une impression du catalogue (`CardRead.card_set_ids`), sinon 404.
             */
            card_set_id: number;
        };
        /**
         * DeckCardRead
         * @description Une ligne de decklist.
         */
        DeckCardRead: {
            /** Card Id */
            card_id: number;
            /** Language Code */
            language_code: string;
            /**
             * Card Set Id
             * @description Extension de l'entrée de collection allouée.
             */
            card_set_id: number;
            /** Quantity */
            quantity: number;
            /**
             * Proxy Quantity
             * @description Part des exemplaires ci-dessus jouée en proxy.
             */
            proxy_quantity: number;
            card: components["schemas"]["CardSummary"] | null;
        };
        /**
         * DeckCardUpdate
         * @description Modification d'une ligne de decklist.
         *
         *     Le contrôle `proxy_quantity <= quantity` n'est complet que si les deux
         *     valeurs sont fournies. Sinon la comparaison porterait sur une valeur que
         *     seule la base connaît : **le service du Lot 2 doit refaire la vérification**
         *     après fusion avec la ligne existante (la contrainte `CHECK` de `deck_card`
         *     reste le dernier filet, mais elle produirait un 500 plutôt qu'un 422).
         */
        DeckCardUpdate: {
            /** Quantity */
            quantity?: number;
            /** Proxy Quantity */
            proxy_quantity?: number;
        };
        /**
         * DeckCardUpsertOperation
         * @description Place une carte dans un deck, ou remplace sa ligne.
         *
         *     `data` porte l'état complet voulu de la ligne (`quantity`,
         *     `proxy_quantity`). La carte doit être en collection dans cette langue et
         *     cette extension, les exemplaires disponibles doivent suffire, et un
         *     `proxy_quantity` non nul exige un deck qui autorise les proxies : sinon
         *     `conflict`, comme en ligne. Une extension où la carte n'a pas été imprimée
         *     est refusée (`not_found`).
         */
        DeckCardUpsertOperation: {
            /**
             * Operation Id
             * Format: uuid
             * @description Clé d'idempotence tirée par le client (UUID), fixée à la saisie et jamais réutilisée. Rejouer le même identifiant rend le verdict d'origine sans rien réappliquer.
             */
            operation_id: string;
            /**
             * Recorded At
             * Format: date-time
             * @description Instant de la saisie à l'horloge du client, fuseau obligatoire, normalisé en UTC. Journalisé ; sans effet sur les règles métier.
             */
            recorded_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "deck_card.upsert";
            deck: components["schemas"]["DeckRef"];
            data: components["schemas"]["DeckCardCreate"];
        };
        /**
         * DeckCreate
         * @description Création d'un deck.
         *
         *     Pas de discriminant : il est tiré par le serveur, qui garantit son unicité
         *     au sein du nom. Un client qui l'imposerait entrerait en course avec un
         *     autre, pour un gain nul.
         */
        DeckCreate: {
            /** Name */
            name: string;
            /** Created On */
            created_on?: string | null;
            /** @default draft */
            status?: components["schemas"]["DeckStatus"];
            /** Archetype */
            archetype?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Proxy Allowed
             * @description Autorise à jouer des proxies dans ce deck, selon le tournoi visé (certains les refusent, d'autres les acceptent). Le nombre de proxies est porté par chaque ligne (`proxy_quantity`). Interdit par défaut.
             * @default false
             */
            proxy_allowed?: boolean;
        };
        /**
         * DeckCreateOperation
         * @description Crée un deck saisi hors ligne.
         *
         *     `client_ref` est **obligatoire** : sans elle, aucune des opérations
         *     suivantes de la file ne pourrait désigner le deck, puisque son identifiant
         *     n'existe pas encore. Le discriminant, lui, reste tiré par le serveur
         *     (CLAUDE.md §11) — un client ne le fournit jamais, hors ligne pas plus
         *     qu'en ligne. `data.proxy_allowed` fixe l'autorisation de proxy du deck
         *     (interdite si omise).
         */
        DeckCreateOperation: {
            /**
             * Operation Id
             * Format: uuid
             * @description Clé d'idempotence tirée par le client (UUID), fixée à la saisie et jamais réutilisée. Rejouer le même identifiant rend le verdict d'origine sans rien réappliquer.
             */
            operation_id: string;
            /**
             * Recorded At
             * Format: date-time
             * @description Instant de la saisie à l'horloge du client, fuseau obligatoire, normalisé en UTC. Journalisé ; sans effet sur les règles métier.
             */
            recorded_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "deck.create";
            /**
             * Client Ref
             * @description Référence du deck côté client, unique et jamais réutilisée (UUID attendu). Les opérations suivantes s'en servent pour désigner ce deck, dans ce lot comme dans les suivants.
             */
            client_ref: string;
            data: components["schemas"]["DeckCreate"];
        };
        /**
         * DeckDeleteOperation
         * @description Supprime logiquement un deck archivé (cf. `DELETE /decks/{id}`).
         */
        DeckDeleteOperation: {
            /**
             * Operation Id
             * Format: uuid
             * @description Clé d'idempotence tirée par le client (UUID), fixée à la saisie et jamais réutilisée. Rejouer le même identifiant rend le verdict d'origine sans rien réappliquer.
             */
            operation_id: string;
            /**
             * Recorded At
             * Format: date-time
             * @description Instant de la saisie à l'horloge du client, fuseau obligatoire, normalisé en UTC. Journalisé ; sans effet sur les règles métier.
             */
            recorded_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "deck.delete";
            deck: components["schemas"]["DeckRef"];
        };
        /**
         * DeckDetailRead
         * @description Un deck avec sa composition.
         */
        DeckDetailRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Discriminator
             * @description Quatre chiffres tirés par le serveur, qui distinguent deux decks de même nom. À afficher collé au nom : « Malkavien 2022#8561 ».
             */
            discriminator: string;
            /** Created On */
            created_on: string | null;
            status: components["schemas"]["DeckStatus"];
            /** Archetype */
            archetype: string | null;
            /** Notes */
            notes: string | null;
            /**
             * Proxy Allowed
             * @description Autorise à jouer des proxies dans ce deck, selon le tournoi visé (certains les refusent, d'autres les acceptent). Le nombre de proxies est porté par chaque ligne (`proxy_quantity`).
             */
            proxy_allowed: boolean;
            /**
             * Archived At
             * @description Instant d'archivage (UTC), nul si le deck n'est pas archivé. Un deck archivé sort des listes par défaut et n'est plus modifiable.
             */
            archived_at: string | null;
            /**
             * Deleted At
             * @description Instant de suppression logique (UTC), nul si le deck n'est pas supprimé. Un deck supprimé n'apparaît dans aucune liste, reste lisible par identifiant et n'est plus modifiable.
             */
            deleted_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Cards
             * @default []
             */
            cards: components["schemas"]["DeckCardRead"][];
        };
        /**
         * DeckLegality
         * @description Verdict de légalité d'un deck (CLAUDE.md §5).
         *
         *     Règles vérifiées : crypt ≥ 12 ; crypt sur deux groupes adjacents au plus
         *     (« Any » neutre) ; library entre 60 et 90 ; aucune carte bannie ; aucune
         *     carte pas encore légale. Les seuils voyagent dans la réponse pour que le
         *     front affiche « 58 / 60 » sans les redéfinir de son côté ; `issues` dit, en
         *     clair, chaque règle enfreinte.
         *
         *     Le verdict est daté (`evaluated_on`) : bannissements et entrées en légalité
         *     dépendent du jour où l'on regarde.
         */
        DeckLegality: {
            /** Deck Id */
            deck_id: number;
            /**
             * Evaluated On
             * Format: date
             * @description Date à laquelle le verdict a été rendu (bans, légalité).
             */
            evaluated_on: string;
            /** Crypt Count */
            crypt_count: number;
            /** Library Count */
            library_count: number;
            /** Crypt Minimum */
            crypt_minimum: number;
            /** Library Minimum */
            library_minimum: number;
            /** Library Maximum */
            library_maximum: number;
            /**
             * Crypt Groups
             * @description Groupes présents dans la crypt, au format des cartes (« G2 »), sans doublon, triés par numéro, « Any » exclu.
             * @default []
             */
            crypt_groups: string[];
            /**
             * Banned Cards
             * @description Cartes du deck bannies à la date d'évaluation. Des cartes entières et non des noms : « Theo Bell » ne désigne rien sans son groupe.
             * @default []
             */
            banned_cards: components["schemas"]["CardSummary"][];
            /**
             * Not Yet Legal Cards
             * @description Cartes dont la date d'entrée en légalité est postérieure à la date d'évaluation : imprimées, mais pas encore jouables.
             * @default []
             */
            not_yet_legal_cards: components["schemas"]["CardSummary"][];
            /** Is Legal */
            is_legal: boolean;
            /**
             * Issues
             * @default []
             */
            issues: string[];
        };
        /**
         * DeckListState
         * @description Quels decks une liste renvoie.
         *
         *     Purement contractuel (pas de colonne en face) : l'archivage est une date,
         *     pas un statut. Les decks supprimés ne sont dans aucun de ces trois cas.
         * @enum {string}
         */
        DeckListState: "active" | "archived" | "all";
        /**
         * DeckRead
         * @description Un deck, sans sa composition.
         */
        DeckRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Discriminator
             * @description Quatre chiffres tirés par le serveur, qui distinguent deux decks de même nom. À afficher collé au nom : « Malkavien 2022#8561 ».
             */
            discriminator: string;
            /** Created On */
            created_on: string | null;
            status: components["schemas"]["DeckStatus"];
            /** Archetype */
            archetype: string | null;
            /** Notes */
            notes: string | null;
            /**
             * Proxy Allowed
             * @description Autorise à jouer des proxies dans ce deck, selon le tournoi visé (certains les refusent, d'autres les acceptent). Le nombre de proxies est porté par chaque ligne (`proxy_quantity`).
             */
            proxy_allowed: boolean;
            /**
             * Archived At
             * @description Instant d'archivage (UTC), nul si le deck n'est pas archivé. Un deck archivé sort des listes par défaut et n'est plus modifiable.
             */
            archived_at: string | null;
            /**
             * Deleted At
             * @description Instant de suppression logique (UTC), nul si le deck n'est pas supprimé. Un deck supprimé n'apparaît dans aucune liste, reste lisible par identifiant et n'est plus modifiable.
             */
            deleted_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DeckRef
         * @description Désignation d'un deck : son identifiant serveur, ou sa référence client.
         *
         *     Exactement l'un des deux. `deck_id` pour un deck que le client a déjà vu
         *     revenir du serveur ; `client_ref` pour un deck créé hors ligne, dont
         *     l'identifiant n'existe pas encore au moment où la file est constituée.
         */
        DeckRef: {
            /** Deck Id */
            deck_id?: number | null;
            /**
             * Client Ref
             * @description Référence donnée par le client au deck lors de sa création hors ligne (`deck.create`). Résolue par le serveur, dans ce lot ou dans un lot antérieur.
             */
            client_ref?: string | null;
        };
        /**
         * DeckStatus
         * @description Avancement d'un deck côté joueur : brouillon ou jouable.
         *
         *     Volontairement réduit à deux valeurs. « Rangé » et « supprimé » ne sont pas
         *     des statuts mais des dates (`deck.archived_at`, `deck.deleted_at`) : un deck
         *     archivé garde le statut qu'il avait, et le désarchiver ne demande donc pas
         *     de deviner lequel.
         * @enum {string}
         */
        DeckStatus: "draft" | "active";
        /**
         * DeckUpdate
         * @description Modification partielle d'un deck.
         *
         *     `name`, `status`, `proxy_allowed` et `archived` sont facultatifs mais non
         *     nullables ;
         *     `created_on`, `archetype` et `notes` acceptent `null` pour effacer la
         *     valeur. Le discriminant ne se modifie pas : renommer un deck ne change pas
         *     son identité (le serveur n'en retire un autre que si le nouveau couple est
         *     déjà pris).
         */
        DeckUpdate: {
            /** Name */
            name?: string;
            /** Created On */
            created_on?: string | null;
            status?: components["schemas"]["DeckStatus"];
            /** Archetype */
            archetype?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Proxy Allowed
             * @description Autorise (`true`) ou interdit (`false`) les proxies dans ce deck. Interdire est refusé tant qu'une ligne du deck en joue.
             */
            proxy_allowed?: boolean;
            /**
             * Archived
             * @description Range le deck (`true`) ou le sort de l'archive (`false`). Pose ou efface `archived_at` ; un deck archivé n'est plus modifiable.
             */
            archived?: boolean;
        };
        /**
         * DeckUpdateOperation
         * @description Modifie un deck — y compris pour l'archiver ou le désarchiver.
         *
         *     `data` suit la sémantique de `PATCH /decks/{id}` : seuls les champs fournis
         *     sont appliqués, et `archived` range ou sort de l'archive. Passer le deck à
         *     `active` exige qu'il soit légal, comme en ligne ; passer `proxy_allowed` à
         *     `false` est refusé (`conflict`) tant qu'une ligne du deck joue un proxy.
         */
        DeckUpdateOperation: {
            /**
             * Operation Id
             * Format: uuid
             * @description Clé d'idempotence tirée par le client (UUID), fixée à la saisie et jamais réutilisée. Rejouer le même identifiant rend le verdict d'origine sans rien réappliquer.
             */
            operation_id: string;
            /**
             * Recorded At
             * Format: date-time
             * @description Instant de la saisie à l'horloge du client, fuseau obligatoire, normalisé en UTC. Journalisé ; sans effet sur les règles métier.
             */
            recorded_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "deck.update";
            deck: components["schemas"]["DeckRef"];
            data: components["schemas"]["DeckUpdate"];
        };
        /**
         * DisciplineRead
         * @description Discipline.
         */
        DisciplineRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Abbrev */
            abbrev: string | null;
        };
        /**
         * DisciplineRequirement
         * @description Manière dont une carte de library combine ses disciplines requises.
         *
         *     `MONO` : une seule discipline (ou aucune). `CHOICE` : l'une au choix
         *     parmi plusieurs. `COMBO` : toutes exigées ensemble. Remplace le champ
         *     textuel brut qu'imposaient les CSV, où « / » et « & » portaient cette
         *     nuance.
         * @enum {string}
         */
        DisciplineRequirement: "mono" | "choice" | "combo";
        /**
         * ErrorResponse
         * @description Corps d'une réponse d'erreur métier.
         */
        ErrorResponse: {
            /**
             * Detail
             * @description Explication lisible de l'échec.
             */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Réponse de `GET /health`.
         */
        HealthResponse: {
            /** @description État courant du service. */
            status: components["schemas"]["HealthStatus"];
            /**
             * Version
             * @description Version de l'API (depuis pyproject.toml).
             */
            version: string;
        };
        /**
         * HealthStatus
         * @description État de disponibilité rapporté par l'API.
         * @enum {string}
         */
        HealthStatus: "ok";
        /**
         * LanguageCreate
         * @description Ajout d'une langue.
         */
        LanguageCreate: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /**
             * Sort Order
             * @description Rang d'affichage, croissant. Le dernier entier borné du contrat.
             * @default 0
             */
            sort_order?: number;
        };
        /**
         * LanguageRead
         * @description Une langue d'exemplaire.
         *
         *     Liste ouverte servie par l'API plutôt que codée en dur dans le front : le
         *     jeu exact des langues reste à confirmer (CLAUDE.md §11 point 2), et une
         *     langue ajoutée en base doit apparaître dans l'UI sans redéploiement.
         */
        LanguageRead: {
            /**
             * Code
             * @description Code court de la langue (EN, FR, ES, XX…).
             */
            code: string;
            /**
             * Label
             * @description Libellé affichable.
             */
            label: string;
            /**
             * Sort Order
             * @description Ordre d'affichage dans les sélecteurs.
             */
            sort_order: number;
        };
        /**
         * PrintOccurrence
         * @description Manière dont une carte apparaît dans une extension.
         *
         *     Les trois cas sont disjoints dans le catalogue krcg et n'utilisent pas les
         *     mêmes champs : `RARITY` porte une fréquence et un multiplicateur (booster),
         *     `PRECON` un produit et un nombre d'exemplaires, `SINGLE` une date de mise
         *     en vente (promo, impression à la demande).
         * @enum {string}
         */
        PrintOccurrence: "rarity" | "precon" | "single";
        /**
         * SectRead
         * @description Sect.
         */
        SectRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * StockDeleteOperation
         * @description Retire une entrée de collection.
         *
         *     Refusée (`conflict`) tant qu'un deck vivant l'utilise, comme
         *     `DELETE /stock/{card_id}/{language_code}/{card_set_id}`.
         */
        StockDeleteOperation: {
            /**
             * Operation Id
             * Format: uuid
             * @description Clé d'idempotence tirée par le client (UUID), fixée à la saisie et jamais réutilisée. Rejouer le même identifiant rend le verdict d'origine sans rien réappliquer.
             */
            operation_id: string;
            /**
             * Recorded At
             * Format: date-time
             * @description Instant de la saisie à l'horloge du client, fuseau obligatoire, normalisé en UTC. Journalisé ; sans effet sur les règles métier.
             */
            recorded_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "stock.delete";
            /** Card Id */
            card_id: number;
            /** Language Code */
            language_code: string;
            /**
             * Card Set Id
             * @description Extension de l'impression (`GET /extensions`). Le couple carte × extension doit être une impression du catalogue (`CardRead.card_set_ids`), sinon 404.
             */
            card_set_id: number;
        };
        /**
         * StockUpsertOperation
         * @description Crée ou remplace une entrée de collection (carte × langue × extension).
         *
         *     `data` porte l'**état complet voulu** de l'entrée : les champs omis
         *     reprennent leur valeur par défaut (0 exemplaire, pas de note), ils ne
         *     conservent pas ce que le serveur avait. C'est ce qui rend l'opération
         *     indifférente à l'ordre du rejeu.
         *
         *     Les règles de stock restent celles du serveur : descendre
         *     `quantity_owned` sous ce que les decks ont déjà alloué est refusé
         *     (`conflict`), et une extension où la carte n'a pas été imprimée est
         *     refusée (`not_found`), comme une carte ou une langue inconnue.
         *     L'autorisation de proxy n'est plus une propriété de l'entrée de collection
         *     (Lot 4) : elle voyage avec le deck (`deck.create`, `deck.update`).
         */
        StockUpsertOperation: {
            /**
             * Operation Id
             * Format: uuid
             * @description Clé d'idempotence tirée par le client (UUID), fixée à la saisie et jamais réutilisée. Rejouer le même identifiant rend le verdict d'origine sans rien réappliquer.
             */
            operation_id: string;
            /**
             * Recorded At
             * Format: date-time
             * @description Instant de la saisie à l'horloge du client, fuseau obligatoire, normalisé en UTC. Journalisé ; sans effet sur les règles métier.
             */
            recorded_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "stock.upsert";
            data: components["schemas"]["CardCopyCreate"];
        };
        /**
         * SyncErrorCode
         * @description Motif de refus d'une opération, lisible par la machine.
         *
         *     Les trois premiers reprennent les erreurs métier des services
         *     (`app.services.errors`), qui restent la seule autorité sur les règles :
         *     `not_found` ← `NotFoundError`, `conflict` ← `ConflictError`, `invalid` ←
         *     `InvalidRequestError`. Les deux derniers sont propres à la
         *     synchronisation.
         * @enum {string}
         */
        SyncErrorCode: "not_found" | "conflict" | "invalid" | "unresolved_client_ref" | "mismatched_replay";
        /**
         * SyncOperationError
         * @description Motif de refus d'une opération.
         *
         *     `code` est fait pour le code du client (router l'opération vers une file
         *     « à corriger », par exemple), `message` pour l'utilisateur : c'est le texte
         *     du service qui a refusé, celui-là même que la route en ligne aurait mis
         *     dans son 404 ou son 409.
         */
        SyncOperationError: {
            code: components["schemas"]["SyncErrorCode"];
            /** Message */
            message: string;
        };
        /**
         * SyncOperationResult
         * @description Verdict rendu sur une opération du lot.
         */
        SyncOperationResult: {
            /**
             * Operation Id
             * Format: uuid
             */
            operation_id: string;
            type: components["schemas"]["SyncOperationType"];
            outcome: components["schemas"]["SyncOutcome"];
            /**
             * Client Ref
             * @description Référence client de l'opération, renvoyée telle quelle. Avec `resource.deck_id`, c'est la correspondance que le client doit enregistrer pour ses prochaines requêtes.
             */
            client_ref: string | null;
            /** @description Ressource touchée ; nul si l'opération a été refusée. */
            resource: components["schemas"]["SyncResourceRef"] | null;
            /** @description Motif du refus ; nul si l'opération a abouti. Une opération `replayed` peut en porter un : c'est alors le refus mémorisé. */
            error: components["schemas"]["SyncOperationError"] | null;
            /**
             * Processed At
             * Format: date-time
             * @description Instant du verdict (UTC). Pour une opération rejouée, c'est celui du verdict d'origine, pas celui de ce rejeu.
             */
            processed_at: string;
        };
        /**
         * SyncOperationType
         * @description Écritures qu'une file hors ligne peut rejouer par `POST /sync` (Lot 3).
         *
         *     Une valeur par intention de l'utilisateur, limitée aux ressources qui
         *     existent déjà : collection, decks, composition, versement d'un produit. Le
         *     catalogue reste en lecture seule (il ne bouge que par l'import, CLAUDE.md
         *     §11) et les parties, tournois et participations attendent le Lot 4 — les
         *     ajouter ici avant qu'elles aient une route serait promettre une
         *     synchronisation sans destination.
         *
         *     Les langues n'y sont pas non plus : `POST /langues` reste une écriture en
         *     ligne. Une saisie hors ligne dans une langue inconnue du serveur doit se
         *     rabattre sur « XX » (autre), cf. le point ouvert du rapport de lot.
         *
         *     Deux nuances de vocabulaire par rapport aux routes REST :
         *
         *     * `stock.upsert` et `deck_card.upsert` créent **ou** remplacent l'entrée,
         *       là où REST distingue `POST` et `PATCH`. Une file rejouée n'a pas de
         *       garantie sur ce que le serveur possède déjà ; l'upsert rend l'ordre des
         *       opérations indifférent et la charge utile porte l'état complet voulu.
         *     * il n'y a pas d'opération d'archivage : archiver, c'est `deck.update` avec
         *       `archived`, exactement comme `PATCH /decks/{id}`.
         * @enum {string}
         */
        SyncOperationType: "stock.upsert" | "stock.delete" | "deck.create" | "deck.update" | "deck.delete" | "deck_card.upsert" | "deck_card.delete" | "bundle.deposit";
        /**
         * SyncOutcome
         * @description Issue d'une opération, du point de vue du client.
         *
         *     `REPLAYED` n'est pas un état stocké (le journal ne connaît que « appliquée »
         *     et « refusée ») : c'est la façon dont le serveur a répondu — il a retrouvé
         *     la clé d'idempotence et rendu le verdict d'alors sans rien refaire. Ce
         *     verdict peut très bien avoir été un refus : `error` le dit.
         * @enum {string}
         */
        SyncOutcome: "applied" | "replayed" | "rejected";
        /**
         * SyncRequest
         * @description Un lot d'opérations à rejouer, dans l'ordre où elles ont été saisies.
         */
        SyncRequest: {
            /**
             * Operations
             * @description Opérations à appliquer dans l'ordre donné. L'ordre compte : une carte ne s'ajoute qu'à un deck déjà créé.
             */
            operations: (components["schemas"]["StockUpsertOperation"] | components["schemas"]["StockDeleteOperation"] | components["schemas"]["DeckCreateOperation"] | components["schemas"]["DeckUpdateOperation"] | components["schemas"]["DeckDeleteOperation"] | components["schemas"]["DeckCardUpsertOperation"] | components["schemas"]["DeckCardDeleteOperation"] | components["schemas"]["BundleDepositOperation"])[];
        };
        /**
         * SyncResourceKind
         * @description Nature de la ressource touchée par une opération de synchronisation.
         * @enum {string}
         */
        SyncResourceKind: "card_copy" | "deck" | "deck_card" | "bundle";
        /**
         * SyncResourceRef
         * @description Identité de la ressource touchée par une opération.
         *
         *     Volontairement réduite à des identifiants : la réponse ne renvoie pas les
         *     objets. Un versement de produit touche des centaines d'entrées de
         *     collection, et le client est en ligne au moment où il synchronise — il
         *     rafraîchit par les `GET` existants. Ce dont il a réellement besoin ici,
         *     c'est du `deck_id` attribué à un deck créé hors ligne.
         */
        SyncResourceRef: {
            kind: components["schemas"]["SyncResourceKind"];
            /** Deck Id */
            deck_id: number | null;
            /** Card Id */
            card_id: number | null;
            /** Language Code */
            language_code: string | null;
            /**
             * Card Set Id
             * @description Extension de l'entrée touchée (`stock.*`, `deck_card.*`). Nulle pour un deck, un versement de produit, ou une opération journalisée avant le Lot 4.
             */
            card_set_id: number | null;
            /** Bundle Id */
            bundle_id: number | null;
        };
        /**
         * SyncResult
         * @description Réponse de `POST /sync` : un verdict par opération, dans le même ordre.
         */
        SyncResult: {
            /**
             * Batch Id
             * Format: uuid
             * @description Identifiant de ce traitement, tiré par le serveur. Sans valeur métier : il sert à relier une trace client à ce qui a été journalisé côté serveur.
             */
            batch_id: string;
            /**
             * Synced At
             * Format: date-time
             * @description Instant du traitement du lot (UTC).
             */
            synced_at: string;
            /**
             * Applied
             * @description Opérations appliquées maintenant.
             */
            applied: number;
            /**
             * Replayed
             * @description Opérations déjà connues, non réappliquées.
             */
            replayed: number;
            /**
             * Rejected
             * @description Opérations refusées, motif à l'appui.
             */
            rejected: number;
            /**
             * Results
             * @description Un résultat par opération reçue, dans l'ordre de la requête.
             * @default []
             */
            results: components["schemas"]["SyncOperationResult"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listCards: {
        parameters: {
            query?: {
                q?: string | null;
                category?: components["schemas"]["CardCategory"] | null;
                clan_id?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardRead"];
                };
            };
            /** @description Ressource introuvable. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listCardSets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardSetRead"][];
                };
            };
        };
    };
    listBundles: {
        parameters: {
            query?: {
                card_set_id?: number | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BundleRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getBundle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bundle_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BundleContentRead"];
                };
            };
            /** @description Ressource introuvable. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    depositBundle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bundle_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BundleDeposit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardCopyRead"][];
                };
            };
            /** @description Ressource introuvable. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflit avec l'état des données (doublon, stock, règle). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listLanguages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LanguageRead"][];
                };
            };
        };
    };
    createLanguage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LanguageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LanguageRead"];
                };
            };
            /** @description Conflit avec l'état des données (doublon, stock, règle). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listStock: {
        parameters: {
            query?: {
                language_code?: string | null;
                card_set_id?: number | null;
                category?: components["schemas"]["CardCategory"] | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardCopyRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createStockEntry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardCopyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardCopyRead"];
                };
            };
            /** @description Ressource introuvable. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflit avec l'état des données (doublon, stock, règle). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getStockEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: number;
                language_code: string;
                card_set_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardCopyRead"];
                };
            };
            /** @description Ressource introuvable. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteStockEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: number;
                language_code: string;
                card_set_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ressource introuvable. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflit avec l'état des données (doublon, stock, règle). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateStockEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: number;
                language_code: string;
                card_set_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardCopyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardCopyRead"];
                };
            };
            /** @description Ressource introuvable. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflit avec l'état des données (doublon, stock, règle). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listDecks: {
        parameters: {
            query?: {
                status?: components["schemas"]["DeckStatus"] | null;
                q?: string | null;
                state?: components["schemas"]["DeckListState"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createDeck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeckCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckRead"];
                };
            };
            /** @description Conflit avec l'état des données (doublon, stock, règle). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getDeck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckDetailRead"];
                };
            };
            /** @description Ressource introuvable. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteDeck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ressource introuvable. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflit avec l'état des données (doublon, stock, règle). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateDeck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeckUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckRead"];
                };
            };
            /** @description Ressource introuvable. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflit avec l'état des données (doublon, stock, règle). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getDeckLegality: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckLegality"];
                };
            };
            /** @description Ressource introuvable. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflit avec l'état des données (doublon, stock, règle). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    addDeckCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeckCardCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckCardRead"];
                };
            };
            /** @description Ressource introuvable. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflit avec l'état des données (doublon, stock, règle). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    removeDeckCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: number;
                card_id: number;
                language_code: string;
                card_set_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ressource introuvable. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflit avec l'état des données (doublon, stock, règle). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateDeckCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: number;
                card_id: number;
                language_code: string;
                card_set_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeckCardUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckCardRead"];
                };
            };
            /** @description Ressource introuvable. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflit avec l'état des données (doublon, stock, règle). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    syncOperations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Une autre écriture tient la base : rien n'a été appliqué. Erreur transitoire, jamais un refus — la requête se renvoie telle quelle, après le délai de l'en-tête `Retry-After`. */
            503: {
                headers: {
                    /** @description Délai conseillé avant de renvoyer la requête, en secondes. */
                    "Retry-After": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
