/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vérifie la disponibilité de l'API
         * @description Sonde de connectivité : sert de test de bout en bout du squelette (Lot 0) et, plus tard, de vérification réseau côté PWA offline-first.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * HealthResponse
         * @description Réponse de `GET /health`.
         */
        HealthResponse: {
            /** @description État courant du service. */
            status: components["schemas"]["HealthStatus"];
            /**
             * Version
             * @description Version de l'API (depuis pyproject.toml).
             */
            version: string;
        };
        /**
         * HealthStatus
         * @description État de disponibilité rapporté par l'API.
         * @enum {string}
         */
        HealthStatus: "ok";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
