// @vitest-environment node
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import openapiTS, { astToString, COMMENT_HEADER } from "openapi-typescript";
import { describe, expect, it } from "vitest";

/**
 * Contract-first côté front (CLAUDE.md §7, §10) : `schema.d.ts` est généré et
 * ne doit jamais être édité ni laissé en retard sur `contracts/openapi.json`.
 *
 * La CI vérifie déjà que `contracts/openapi.json` suit l'application
 * (`export_openapi.py --check`), mais rien ne vérifiait le second maillon :
 * contrat -> types TypeScript. Ce test régénère les types en mémoire avec les
 * options de `npm run generate:client` (dont `--default-non-nullable false`,
 * voir `contracts/README.md`) et exige l'égalité octet à
 * octet (fins de ligne normalisées) avec le fichier versionné.
 *
 * En cas d'échec : `npm run generate:client` puis committer le résultat.
 */
const FRONTEND_DIR = resolve(__dirname, "../../..");
const CONTRACT_PATH = resolve(FRONTEND_DIR, "../contracts/openapi.json");
const SCHEMA_PATH = resolve(FRONTEND_DIR, "src/api-client/schema.d.ts");

const normalize = (text: string) => text.replace(/\r\n/g, "\n");

describe("client TS généré", () => {
  it("schema.d.ts est identique à ce que génère contracts/openapi.json", async () => {
    const contract = JSON.parse(readFileSync(CONTRACT_PATH, "utf-8"));

    const generated =
      COMMENT_HEADER + astToString(await openapiTS(contract, {
        silent: true,
        defaultNonNullable: false,
      }));
    const committed = readFileSync(SCHEMA_PATH, "utf-8");

    expect(normalize(committed)).toBe(normalize(generated));
  });

  it("le fichier généré porte l'avertissement « ne pas modifier »", () => {
    const committed = readFileSync(SCHEMA_PATH, "utf-8");
    expect(committed).toContain("auto-generated by openapi-typescript");
    expect(committed).toContain("Do not make direct changes to the file");
  });

  it("expose une opération par chemin du contrat (aucune route oubliée)", () => {
    const contract = JSON.parse(readFileSync(CONTRACT_PATH, "utf-8"));
    const committed = readFileSync(SCHEMA_PATH, "utf-8");

    for (const path of Object.keys(contract.paths)) {
      expect(committed).toContain(`"${path}":`);
    }
    for (const methods of Object.values<Record<string, { operationId?: string }>>(
      contract.paths,
    )) {
      for (const operation of Object.values(methods)) {
        if (operation.operationId) {
          expect(committed).toContain(operation.operationId);
        }
      }
    }
  });
});
