"""Schéma initial du suivi VtES

Crée les 21 tables du modèle (catalogue, produits, collection, decks, parties,
tournois, références) et insère les langues de départ.

Révision autogénérée puis relue à la main. Deux ajouts manuels :

* les données de départ de `language` — la liste des langues n'est pas figée
  dans le code (CLAUDE.md §11 point 2, énumération « à confirmer »), donc
  quatre lignes suffisent à démarrer et une cinquième langue s'ajoutera par
  simple `INSERT`, sans migration de schéma ;
* le `downgrade` supprime tout, y compris ces données — c'est cohérent pour
  une révision initiale : revenir à `base`, c'est revenir à une base vide.

Revision ID: a59a3613de12
Revises:
Create Date: 2026-09-18 22:31:12.870610

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Identifiants de révision utilisés par Alembic.
revision: str = 'a59a3613de12'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abbrev', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('company', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_set')),
    sa.UniqueConstraint('abbrev', name=op.f('uq_card_set_abbrev'))
    )
    op.create_table('bundle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_set_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.CheckConstraint('size >= 1', name=op.f('ck_bundle_size_positive')),
    sa.ForeignKeyConstraint(['card_set_id'], ['card_set.id'], name=op.f('fk_bundle_card_set_id_card_set')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bundle')),
    sa.UniqueConstraint('card_set_id', 'code', name=op.f('uq_bundle_card_set_id_code'))
    )
    op.create_table('card_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_type')),
    sa.UniqueConstraint('name', name=op.f('uq_card_type_name'))
    )
    op.create_table('clan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('abbrev', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clan')),
    sa.UniqueConstraint('name', name=op.f('uq_clan_name'))
    )
    op.create_table('deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_on', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'retired', name='deck_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('archetype', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deck')),
    sa.UniqueConstraint('name', name=op.f('uq_deck_name'))
    )
    op.create_table('discipline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('abbrev', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discipline')),
    sa.UniqueConstraint('name', name=op.f('uq_discipline_name'))
    )
    op.create_table('language',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_language'))
    )
    op.bulk_insert(
        sa.table(
            'language',
            sa.column('code', sa.String),
            sa.column('label', sa.String),
            sa.column('sort_order', sa.Integer),
        ),
        [
            {'code': 'EN', 'label': 'Anglais', 'sort_order': 10},
            {'code': 'FR', 'label': 'Français', 'sort_order': 20},
            {'code': 'ES', 'label': 'Espagnol', 'sort_order': 30},
            {'code': 'XX', 'label': 'Autre', 'sort_order': 99},
        ],
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_me', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player')),
    sa.UniqueConstraint('name', name=op.f('uq_player_name'))
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_index('ux_player_is_me', ['is_me'], unique=True, sqlite_where=sa.text('is_me = 1'))

    op.create_table('sect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sect')),
    sa.UniqueConstraint('name', name=op.f('uq_sect_name'))
    )
    op.create_table('venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venue')),
    sa.UniqueConstraint('name', name=op.f('uq_venue_name'))
    )
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vekn_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('category', sa.Enum('crypt', 'library', name='card_category', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('clan_id', sa.Integer(), nullable=True),
    sa.Column('sect_id', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('group_code', sa.String(length=8), nullable=True),
    sa.Column('advanced', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('cost_type', sa.Enum('pool', 'blood', 'conviction', name='cost_type', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('cost_value', sa.String(length=4), nullable=True),
    sa.Column('burn_option', sa.Boolean(), nullable=False),
    sa.Column('trifle', sa.Boolean(), nullable=False),
    sa.Column('clan_requirement', sa.String(length=120), nullable=True),
    sa.Column('path_requirement', sa.String(length=60), nullable=True),
    sa.Column('discipline_requirement', sa.Enum('mono', 'choice', 'combo', name='discipline_requirement', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('path', sa.String(length=60), nullable=True),
    sa.Column('card_text', sa.Text(), nullable=True),
    sa.Column('flavor_text', sa.Text(), nullable=True),
    sa.Column('artist', sa.String(length=120), nullable=True),
    sa.Column('banned_on', sa.Date(), nullable=True),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['clan_id'], ['clan.id'], name=op.f('fk_card_clan_id_clan')),
    sa.ForeignKeyConstraint(['sect_id'], ['sect.id'], name=op.f('fk_card_sect_id_sect')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card')),
    sa.UniqueConstraint('vekn_id', name=op.f('uq_card_vekn_id'))
    )
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.create_index('ix_card_name', ['name'], unique=False)

    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('deck_policy', sa.Enum('mono', 'multi', name='deck_policy', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('format', sa.Enum('constructed', 'draft', 'other', name='tournament_format', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('round_count', sa.Integer(), nullable=True),
    sa.Column('my_ranking', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('round_count >= 1', name=op.f('ck_tournament_round_count_positive')),
    sa.CheckConstraint('my_ranking >= 1', name=op.f('ck_tournament_my_ranking_positive')),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], name=op.f('fk_tournament_venue_id_venue')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournament'))
    )
    op.create_table('card_copy',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=8), nullable=False),
    sa.Column('quantity_owned', sa.Integer(), nullable=False),
    sa.Column('proxy_allowed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('quantity_owned >= 0', name=op.f('ck_card_copy_quantity_owned_positive')),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], name=op.f('fk_card_copy_card_id_card')),
    sa.ForeignKeyConstraint(['language_code'], ['language.code'], name=op.f('fk_card_copy_language_code_language')),
    sa.PrimaryKeyConstraint('card_id', 'language_code', name=op.f('pk_card_copy'))
    )
    op.create_table('card_discipline_link',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('superior', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], name=op.f('fk_card_discipline_link_card_id_card'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['discipline_id'], ['discipline.id'], name=op.f('fk_card_discipline_link_discipline_id_discipline')),
    sa.PrimaryKeyConstraint('card_id', 'discipline_id', name=op.f('pk_card_discipline_link'))
    )
    op.create_table('card_printing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('card_set_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], name=op.f('fk_card_printing_card_id_card'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['card_set_id'], ['card_set.id'], name=op.f('fk_card_printing_card_set_id_card_set')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_printing')),
    sa.UniqueConstraint('card_id', 'card_set_id', name=op.f('uq_card_printing_card_id_card_set_id'))
    )
    op.create_table('card_printing_occurrence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_printing_id', sa.Integer(), nullable=False),
    sa.Column('occurrence_type', sa.Enum('rarity', 'precon', 'single', name='print_occurrence', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('frequency', sa.String(length=4), nullable=True),
    sa.Column('multiplier', sa.Float(), nullable=True),
    sa.Column('bundle_id', sa.Integer(), nullable=True),
    sa.Column('copies', sa.Integer(), nullable=True),
    sa.Column('released_on', sa.Date(), nullable=True),
    sa.CheckConstraint('copies >= 1', name=op.f('ck_card_printing_occurrence_copies_positive')),
    sa.CheckConstraint('multiplier > 0', name=op.f('ck_card_printing_occurrence_multiplier_positive')),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundle.id'], name=op.f('fk_card_printing_occurrence_bundle_id_bundle')),
    sa.ForeignKeyConstraint(['card_printing_id'], ['card_printing.id'], name=op.f('fk_card_printing_occurrence_card_printing_id_card_printing'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_printing_occurrence'))
    )
    with op.batch_alter_table('card_printing_occurrence', schema=None) as batch_op:
        batch_op.create_index('ix_card_printing_occurrence_bundle_id', ['bundle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_printing_occurrence_card_printing_id'), ['card_printing_id'], unique=False)

    op.create_table('card_translation',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('card_text', sa.Text(), nullable=True),
    sa.Column('flavor_text', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], name=op.f('fk_card_translation_card_id_card'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language_code'], ['language.code'], name=op.f('fk_card_translation_language_code_language')),
    sa.PrimaryKeyConstraint('card_id', 'language_code', name=op.f('pk_card_translation'))
    )
    op.create_table('card_type_link',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('card_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], name=op.f('fk_card_type_link_card_id_card'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['card_type_id'], ['card_type.id'], name=op.f('fk_card_type_link_card_type_id_card_type')),
    sa.PrimaryKeyConstraint('card_id', 'card_type_id', name=op.f('pk_card_type_link'))
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('round_type', sa.Enum('casual', 'preliminary', 'final', name='round_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('player_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('player_count >= 2', name=op.f('ck_game_player_count_minimum')),
    sa.CheckConstraint('round_number >= 1', name=op.f('ck_game_round_number_positive')),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], name=op.f('fk_game_tournament_id_tournament')),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], name=op.f('fk_game_venue_id_venue')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game'))
    )
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_tournament_id'), ['tournament_id'], unique=False)

    op.create_table('deck_card',
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('proxy_quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('proxy_quantity >= 0 AND proxy_quantity <= quantity', name=op.f('ck_deck_card_proxy_quantity_within_quantity')),
    sa.CheckConstraint('quantity >= 1', name=op.f('ck_deck_card_quantity_positive')),
    sa.ForeignKeyConstraint(['card_id', 'language_code'], ['card_copy.card_id', 'card_copy.language_code'], name=op.f('fk_deck_card_card_id_language_code_card_copy')),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], name=op.f('fk_deck_card_deck_id_deck'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deck_id', 'card_id', 'language_code', name=op.f('pk_deck_card'))
    )
    with op.batch_alter_table('deck_card', schema=None) as batch_op:
        batch_op.create_index('ix_deck_card_card_id_language_code', ['card_id', 'language_code'], unique=False)

    op.create_table('participation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.Column('seat', sa.Integer(), nullable=True),
    sa.Column('victory_points', sa.Float(), nullable=True),
    sa.Column('game_win', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('seat >= 1', name=op.f('ck_participation_seat_positive')),
    sa.CheckConstraint('victory_points >= 0', name=op.f('ck_participation_victory_points_positive')),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], name=op.f('fk_participation_deck_id_deck')),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_participation_game_id_game'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('fk_participation_player_id_player')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participation')),
    sa.UniqueConstraint('game_id', 'player_id', name=op.f('uq_participation_game_id_player_id')),
    sa.UniqueConstraint('game_id', 'seat', name=op.f('uq_participation_game_id_seat'))
    )
    with op.batch_alter_table('participation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participation_deck_id'), ['deck_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participation_deck_id'))

    op.drop_table('participation')
    with op.batch_alter_table('deck_card', schema=None) as batch_op:
        batch_op.drop_index('ix_deck_card_card_id_language_code')

    op.drop_table('deck_card')
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_tournament_id'))

    op.drop_table('game')
    op.drop_table('card_type_link')
    op.drop_table('card_translation')
    with op.batch_alter_table('card_printing_occurrence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_printing_occurrence_card_printing_id'))
        batch_op.drop_index('ix_card_printing_occurrence_bundle_id')

    op.drop_table('card_printing_occurrence')
    op.drop_table('card_printing')
    op.drop_table('card_discipline_link')
    op.drop_table('card_copy')
    op.drop_table('tournament')
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_index('ix_card_name')

    op.drop_table('card')
    op.drop_table('venue')
    op.drop_table('sect')
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index('ux_player_is_me', sqlite_where=sa.text('is_me = 1'))

    op.drop_table('player')
    op.drop_table('language')
    op.drop_table('discipline')
    op.drop_table('deck')
    op.drop_table('clan')
    op.drop_table('card_type')
    op.drop_table('bundle')
    op.drop_table('card_set')
    # ### end Alembic commands ###
